name: Build

on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create image
      run: make

    - name: Push edge image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag ublbuilder/ubl2-tooling:dev ublbuilder/ubl2-tooling:edge
        docker push ublbuilder/ubl2-tooling:edge

    - name: Push tagged image
      if: startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        TAG=$(echo $GITHUB_REF | sed "s:.*/::g")
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN}
        docker tag ublbuilder/ubl2-tooling:dev ublbuilder/ubl2-tooling:$TAG
        docker push ublbuilder/ubl2-tooling:$TAG
        docker tag ublbuilder/ubl2-tooling:dev ublbuilder/ubl2-tooling:latest
        docker push ublbuilder/ubl2-tooling:latest
